sudo: true

language: node_js

node_js:
  - "6"

addons:
  postgresql: "9.4"
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

env:
  global:
    # Build Settings
    - NODE_ENV=test
    - CXX=g++-4.8

    # App Setttnigs
    - MAXMIND_DB="./tmp/maxmind/GeoLite2-City.mmdb"
    - SEQUELIZE_HOST="localhost"
    - SEQUELIZE_DATABASE="messagebot_test"
    - SEQUELIZE_PASSWORD=""
    - REDIS_HOST="127.0.0.1"
    - REDIS_PORT="6379"
    - REDIS_DB="1"
    - REDIS_PASSWORD=""
    - ELASTICSEARCH_VERSION="2.3.4"
    - ELASTICSEARCH_URLS="http://localhost:9200"

    # Flynn Deployment
    - secure: "vGSAR4oqA1uFTAq8oyGBKGCRLMBXkFnZs3wqy/1KB/4YNlBe0BFIxVTKRVNwjNdxG2UrtMqo7xp/XcI0O3YOg+LybtRQ/hnbXxDZeC9I0AEFXvbnBSEhN8cOsifzmQbgXoNXnH4It/69zw3HnJCSuKKNrHYBRiqQIc+VLDfdV/TcBkKzm4P7quePOAmJrqwAjabmvMjh2mLueVN4D6ZQ7/0sj0P9chalxd2iaCJOrquRd+4VU4psE7WzBvb0ExU80uTtEMnpbcFF4JUziDNDCYVB5/xcCFL+f275JcTWRNPuxEyGr+moilrg3VH/jFA30HgcvV8DquMkc7ItgLSK/OeZkBnPJmZB6vCVYfAjMqE+m59olvM3R7BliR3cY0RE+WT5fJJrmoxAqIYRNwUNvPbfCtCp6jmusTBz6RTBeIeL57zjbfDLQWUi4jdr9L3M0drcl03lSQD6WYCWQFhXh02ujWiO3NBheehCDnKDx0BfXei8dSvb6hbP77SR8CCUnYLqiicpQRN2aAKFx/PVKNV+k4NbbGFaY9A0AmeOAJMH96F0z8yr2vhi+8XO4VVkC2t2kr9VkvyhDRGJyXr2JnNkgDUIyLV1QQqvYhLx4N8l+B2pXU2XvxX59kiz5UdCJmFuK3Kv64l4zL/6XWUJHbMkFM5VcdT90wj5+ARpwOQ="

  matrix:
    - SEQUELIZE_DIALECT=mysql    SEQUELIZE_USER=root     SEQUELIZE_PORT=3306
    - SEQUELIZE_DIALECT=postgres SEQUELIZE_USER=postgres SEQUELIZE_PORT=5432

before_install:
  # Install build tools needed for some NPM packages
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 g++-4.8 -y

  # Install Elasticsearch Latest Version
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ELASTICSEARCH_VERSION/elasticsearch-$ELASTICSEARCH_VERSION.deb
  - sudo dpkg -i --force-confnew elasticsearch-$ELASTICSEARCH_VERSION.deb
  - sudo service elasticsearch restart
  # - sleep 10 # (not needed as NPM install takes long enough)

before_script:
  # For some reason, Travis ES comes with a 'tweets' index?!
  - "npm run ui:build"
  - "curl -X DELETE http://localhost:9200/*"

after_success:
  - |
      declare exitCode;

      $(npm bin)/travis-after-all
      exitCode=$?

      if [ $exitCode -eq 0 ]; then
        FLYNN_APP=""

        if [ "$TRAVIS_BRANCH" = "master" ]; then FLYNN_APP="staging"; fi
        if [ "$TRAVIS_BRANCH" = "production" ]; then FLYNN_APP="api"; fi

        if [ "$FLYNN_APP" = "" ]; then echo "skipping branch $TRAVIS_BRANCH" && exit 0; fi

        git pull
        git remote add flynn https://user:$FLYNN_KEY@git.site.com/$FLYNN_APP.git
        git push flynn master
      fi

      if [ $exitCode -eq 1 ]; then
        # BUILD FAILURE
        echo "BUSTED"
      fi

os:
  - linux

script: npm run test

services:
  - redis-server
  - mysql
  - postgresql
  - docker
