sudo: true

language: node_js

os:
  - linux

node_js:
  - "6"

addons:
  apt:
    packages:
    # - mysql-server-5.6
    # - mysql-client-core-5.6
    # - mysql-client-5.6
    - oracle-java8-installer
    - oracle-java8-set-default

services:
  - redis-server
  - mysql

env:
  global:
    # Build Settings
    - NODE_ENV=test
    - CXX=g++-4.8
    - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.2.deb
    - ES_VERSION=5.0.2


    # App Setttnigs
    - MAXMIND_DB="./tmp/maxmind/GeoLite2-City.mmdb"
    - SEQUELIZE_HOST="localhost"
    - SEQUELIZE_DATABASE="messagebot_test"
    - SEQUELIZE_PASSWORD=""
    - REDIS_HOST="127.0.0.1"
    - REDIS_PORT="6379"
    - REDIS_DB="1"
    - REDIS_PASSWORD=""
    - ELASTICSEARCH_VERSION="2.3.4"
    - ELASTICSEARCH_URLS="http://localhost:9200"

  matrix:
    - SEQUELIZE_DIALECT=mysql    SEQUELIZE_USER=root     SEQUELIZE_PORT=3306

before_install:
  # Install build tools needed for some NPM packages
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 g++-4.8 -y

  # Install Elasticsearch Latest Version
  - curl -O $ES_DOWNLOAD_URL
  - sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb
  - sudo service elasticsearch restart
  - sleep 15
  - curl http://localhost:9200

before_script:
  # For some reason, Travis ES comes with a 'tweets' index?!
  - "curl -X DELETE http://localhost:9200/*"

script: npm run test
