sudo: false

language: node_js

node_js:
  - "4.0"
  - "5.0"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

os:
  - linux
  # - osx
  # - windows

script: npm run-script test

services:
  - redis-server
  - mysql
  - elasticsearch

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS doctrine_tests_tmp;create database IF NOT EXISTS messagebot_test;'; fi"
