web:    MIN_TASK_PROCESSORS=0 MAX_TASK_PROCESSORS=0 ENABLE_WEB_SERVER=true  ENABLE_SOCKET_SERVER=true  ENABLE_WEBSOCKET_SERVER=true   npm start
worker: MIN_TASK_PROCESSORS=5 MAX_TASK_PROCESSORS=5 ENABLE_WEB_SERVER=false ENABLE_SOCKET_SERVER=false ENABLE_WEBSOCKET_SERVER=false  npm start
